[project]
name = "condicao-cardiaca"
version = "0.1.0"
description = "Projeto de ciência de dados com o objetivo de realizar a predição e extração de conhecimento de patologias cardíacas em crianças e jovens."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dython>=0.7.12",
    "matplotlib>=3.10.9",
    "missingno>=0.5.2",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
]
